"""
M5 bridge -- export the trained models to JSON the web app can run.

The web app performs REAL inference. It does not call a server and it does not
replay canned answers: it re-implements the exact arithmetic of the deployed
models in TypeScript, using the coefficients written here.

That is only possible because every deployed model is linear:
  * P(any spend)      multinomial-free logistic regression
  * Risk tier         multinomial logistic regression (3 classes, softmax)
  * Expected cost     Tweedie GLM with a log link

A logistic or log-link GLM is a dot product followed by one scalar function, so
a browser can evaluate it in microseconds and, more importantly, can report the
EXACT contribution of every input rather than an approximation of it.

    python3 ml/export_web_model.py
"""
from __future__ import annotations

import json
import shutil

import joblib
import numpy as np
import pandas as pd

from config import (
    ARTIFACTS, CONDITION_LABELS, DISPLAY_CURRENCY, FEATURE_COLUMNS, TIER_NAMES,
    USD_TO_INR, WEB_PUBLIC,
)
from data_prep import build_dataset
from encoder import MepsEncoder

b = joblib.load(ARTIFACTS / "models.joblib")
enc: MepsEncoder = b["encoder"]
scaler = b["scaler_c"]
tier, part1, tweedie = b["tier"], b["part1"], b["tweedie"]

# ---------------------------------------------------------------------------
# The reference person: training median for continuous inputs, training mode
# for categorical ones. All explanations are stated relative to this person.
# ---------------------------------------------------------------------------
train_like = build_dataset(verbose=False)
ref = {c: float(np.nanmedian(train_like[c].astype(float))) for c in FEATURE_COLUMNS}
for c in ("sex", "region", "insurance", "poverty_category", "marital_status",
          "smoking_status"):
    ref[c] = float(train_like[c].mode().iloc[0])
z_ref = scaler.transform(enc.transform(pd.DataFrame([ref])[FEATURE_COLUMNS]))[0]

model = {
    "_comment": "Generated by ml/export_web_model.py. Do not edit by hand.",
    "encoder": enc.to_spec(),
    "scaler": {"mean": scaler.mean_.tolist(), "scale": scaler.scale_.tolist()},
    "reference": {"raw": ref, "z": z_ref.tolist()},
    "tierModel": {
        "type": "multinomial-logistic",
        "classes": TIER_NAMES,
        "coef": tier.coef_.tolist(),
        "intercept": tier.intercept_.tolist(),
    },
    "anySpendModel": {
        "type": "logistic",
        "coef": part1.coef_[0].tolist(),
        "intercept": float(part1.intercept_[0]),
    },
    "costModel": {
        "type": "tweedie-glm-log-link",
        "power": float(tweedie.power),
        "coef": tweedie.coef_.tolist(),
        "intercept": float(tweedie.intercept_),
    },
    # Display currency. The models are trained and stored in USD; the web app
    # converts only at render time, so changing this never changes a prediction.
    "currency": {"code": DISPLAY_CURRENCY, "usdRate": USD_TO_INR},
    "tierCuts": [float(c) for c in b["cuts"]],
    "featureNames": enc.feature_names_,
    "conditionLabels": CONDITION_LABELS,
}

out = WEB_PUBLIC / "model.json"
out.write_text(json.dumps(model))
shutil.copy(ARTIFACTS / "metrics.json", WEB_PUBLIC / "metrics.json")

kb = out.stat().st_size / 1024
print(f"model.json   -> {out}  ({kb:.1f} KB)")
print(f"metrics.json -> {WEB_PUBLIC / 'metrics.json'} "
      f"({(WEB_PUBLIC / 'metrics.json').stat().st_size / 1024:.1f} KB)")

# ---------------------------------------------------------------------------
# Parity check: score a handful of real people through the exported numbers the
# same way the browser will, and confirm we reproduce scikit-learn exactly.
# If this drifts, the web app is lying to the user.
# ---------------------------------------------------------------------------
sample = train_like[FEATURE_COLUMNS].head(200)
Z = (enc.transform(sample) - np.array(model["scaler"]["mean"])) / np.array(
    model["scaler"]["scale"])
logits = Z @ np.array(model["tierModel"]["coef"]).T + np.array(
    model["tierModel"]["intercept"])
manual = np.exp(logits - logits.max(1, keepdims=True))
manual /= manual.sum(1, keepdims=True)
sk = tier.predict_proba(scaler.transform(enc.transform(sample)))
print(f"Tier probability parity   max abs diff: {np.abs(manual - sk).max():.2e}")

manual_cost = np.exp(Z @ np.array(model["costModel"]["coef"])
                     + model["costModel"]["intercept"])
sk_cost = tweedie.predict(scaler.transform(enc.transform(sample)))
print(f"Expected-cost parity      max abs diff: ${np.abs(manual_cost - sk_cost).max():.6f}")
