/**
 * The research page.
 *
 * Every figure on this page is read at runtime from `public/metrics.json`,
 * which `ml/train.py` writes. Nothing is typed in by hand, so the page cannot
 * drift away from the model: retrain, re-export, and the write-up updates
 * itself. If a number here looks wrong, the training run produced it.
 */
import {
  AlertTriangle, BarChart3, Binary, BookOpen, Database, FlaskConical, Gavel,
  GitBranch, Microscope, Scale, ScrollText, Sigma, Target, Users,
} from "lucide-react";
import { CurveChart, ConfusionMatrix, Frame, BarChart, Legend, LiftChart } from "./charts";
import { Note, SectionHeading, Stat, Table, money, pct } from "./ui";
import { FEATURE_LABELS } from "../lib/schema";
import { getRate } from "../lib/currency";

const TIER_COLORS = ["var(--color-low)", "var(--color-medium)", "var(--color-high)"];
const n = (x: number, d = 3) => x.toFixed(d);

function Section({ id, children }: { id: string; children: React.ReactNode }) {
  return <section id={id} className="scroll-mt-24 border-t border-[var(--color-line)] py-12">{children}</section>;
}

export default function Research({ m }: { m: any }) {
  const d = m.dataset;
  const reg = m.regression;
  const cls = m.classification;
  const tiers: string[] = cls.tierNames;

  return (
    <article className="mx-auto max-w-4xl px-4 pb-24 sm:px-6">
      {/* ------------------------------------------------------------- header */}
      <header className="py-14">
        <div className="mb-3 flex items-center gap-2 text-[11px] font-semibold uppercase tracking-[0.14em] text-[var(--color-accent)]">
          <ScrollText size={14} strokeWidth={2.4} /> Research write-up
        </div>
        <h1 className="font-[family-name:var(--font-display)] text-[2.4rem] leading-[1.1] sm:text-[3rem]">
          Predicting and stratifying medical insurance risk
        </h1>
        <p className="mt-4 max-w-2xl text-[16px] leading-relaxed text-[var(--color-ink-soft)]">
          A complete account of the models behind this tool: the data they were
          trained on, the decisions made while building them, the things that did
          not work, and exactly how well they perform on people they had never
          seen. Every number below is generated by the training run, not written
          by hand.
        </p>
        {/* Authorship. Kept next to the title because a research write-up
            should say who is accountable for it. */}
        <div className="mt-8 rounded-xl border border-[var(--color-line)] bg-white p-5">
          <div className="mb-3 flex items-center gap-2 text-[11px] font-semibold uppercase tracking-[0.14em] text-[var(--color-ink-faint)]">
            <Users size={14} strokeWidth={2.4} /> Submitted by
          </div>
          <ul className="grid gap-2 sm:grid-cols-3">
            {[
              ["Rethick C B", "RA2411056010016"],
              ["Anumitha", "RA2411056010012"],
              ["Dheepak S", "RA2411056010007"],
            ].map(([name, reg]) => (
              <li key={reg}>
                <span className="block text-[14px] font-semibold text-[var(--color-ink)]">{name}</span>
                <span className="block font-mono text-[12px] tabular-nums text-[var(--color-ink-faint)]">{reg}</span>
              </li>
            ))}
          </ul>
          <p className="mt-4 border-t border-[var(--color-line)] pt-3 text-[13px] leading-relaxed text-[var(--color-ink-soft)]">
            Department of Data Science and Business Systems<br />
            SRM Institute of Science and Technology, Chennai
          </p>
        </div>

        <div className="mt-6 rounded-xl border-l-2 border-[var(--color-accent)] bg-[var(--color-accent-soft)] px-4 py-3 text-[13.5px] leading-relaxed text-[var(--color-ink-soft)]">
          <strong>A note on currency.</strong> MEPS records US healthcare spending in
          US dollars, and every model here is trained and evaluated in dollars.
          Money is converted for display only, at ₹{getRate()} to the dollar, so the
          currency shown can never change a prediction. Converting a US cost into
          rupees does not make it an Indian cost: the same treatment costs several
          times more in the American system. Read these as US prices in a familiar
          unit. Re-training on Indian claims data would be a separate project, and
          this pipeline would carry over to it.
        </div>
        <p className="mt-4 text-[12.5px] text-[var(--color-ink-faint)]">
          Generated {m.generatedAt} · seed {d.seed} · {d.nFolds}-fold cross-validation ·
          {" "}{pct(d.testSize, 0)} held-out test split
        </p>

        <div className="mt-8 grid gap-3 sm:grid-cols-2 lg:grid-cols-4">
          <Stat label="People analysed" value={d.rowsAdults.toLocaleString()}
            sub={`Adults 18+, from ${d.rowsRaw.toLocaleString()} survey respondents`} />
          <Stat label="Held-out test set" value={d.nTest.toLocaleString()}
            sub="Never seen during training or model selection" />
          <Stat label="Risk tier macro-F1" value={n(cls.perClassMacro ?? bestF1(cls), 3)}
            sub={`vs ${n(baselineF1(cls), 3)} for a random baseline`} />
          <Stat label="Top-decile lift" value={`${reg.topBottomDecileRatio.toFixed(1)}×`}
            sub="Costliest tenth vs cheapest tenth, actual spending" />
        </div>
      </header>

      {/* ------------------------------------------------------------- problem */}
      <Section id="problem">
        <SectionHeading icon={Target} eyebrow="1. The problem" title="Why coarse pricing rules fail">
          An insurer has to price a policy before it knows what the customer will
          cost. Underprice the sick and you lose money; overprice the healthy and
          they leave. Most pricing still leans on age bands and a smoker flag, which
          cannot see how risk factors combine — smoking together with a high BMI
          costs more than either does alone.
        </SectionHeading>
        <div className="grid gap-4 sm:grid-cols-3">
          {[
            { t: "Predict", b: "Expected annual medical spend, in dollars. A regression problem." },
            { t: "Stratify", b: "Sort each person into Low, Medium or High risk. A three-class problem." },
            { t: "Explain", b: "Show which answers drove each individual result, so pricing can be audited." },
          ].map((x) => (
            <div key={x.t} className="card p-4">
              <h3 className="text-[14px] font-semibold">{x.t}</h3>
              <p className="mt-1.5 text-[13px] leading-relaxed text-[var(--color-ink-soft)]">{x.b}</p>
            </div>
          ))}
        </div>
      </Section>

      {/* ---------------------------------------------------------------- data */}
      <Section id="data">
        <SectionHeading icon={Database} eyebrow="2. The data" title="MEPS HC-256, calendar year 2024">
          The Medical Expenditure Panel Survey is run by the US Agency for
          Healthcare Research and Quality. It is real survey data, not a simulation:
          a nationally representative sample of the US civilian non-institutionalised
          population, with actual recorded expenditure. The full-year consolidated
          file has one row per person and {"1,615"} columns.
        </SectionHeading>

        <div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-4">
          <Stat label="Raw rows" value={d.rowsRaw.toLocaleString()} sub="All ages" />
          <Stat label="After filtering to adults" value={d.rowsAdults.toLocaleString()}
            sub="BMI and smoking are adult-only survey items" />
          <Stat label="Zero spenders" value={pct(d.zeroSpendShare, 1)}
            sub="Spent nothing at all during 2024" />
          <Stat label="Target skew" value={d.targetSkew.toFixed(1)}
            sub="A symmetric distribution would be 0" />
        </div>

        <h3 className="mt-8 mb-3 text-[15px] font-semibold">Four problems in the raw file, and what was done about each</h3>
        <div className="space-y-3">
          {[
            {
              p: "Negative values that are not values",
              s: "MEPS codes “inapplicable”, “refused”, “don't know” and “cannot be computed” as −1, −7, −8, −9 and −15. Left alone, a model happily learns that a BMI of −15 predicts something.",
              f: "Every reserved code is converted to NaN before anything else happens.",
            },
            {
              p: "A target that is zero for one person in seven",
              s: `${pct(d.zeroSpendShare, 1)} of adults spent nothing, and the rest are skewed ${d.targetSkew.toFixed(1)} to the right. Ordinary least squares on dollars is the wrong shape for this.`,
              f: "Two approaches were built and compared: a two-part model, and a Tweedie GLM whose distribution has an atom at exactly zero.",
            },
            {
              p: "Adult-only questions",
              s: "BMI and smoking are only collected for adults, so children have no values at all for them.",
              f: "The population is filtered to age 18 and over, which is stated as a scope limit rather than hidden.",
            },
            {
              p: "Heavy missingness in the best features",
              s: "BMI is missing for about 30% of adults and the exercise question for about 29%, because both come from a self-administered questionnaire that not everyone returns.",
              f: "Each feature carries a companion “was this missing?” indicator, so the model can use the fact of non-response as information rather than pretending a median was observed.",
            },
          ].map((x) => (
            <div key={x.p} className="card p-4">
              <h4 className="flex items-center gap-2 text-[14px] font-semibold">
                <AlertTriangle size={14} className="shrink-0 text-[var(--color-medium)]" /> {x.p}
              </h4>
              <p className="mt-1.5 text-[13px] leading-relaxed text-[var(--color-ink-soft)]">{x.s}</p>
              <p className="mt-2 border-l-2 border-[var(--color-accent)] pl-3 text-[13px] leading-relaxed text-[var(--color-ink-soft)]">
                {x.f}
              </p>
            </div>
          ))}
        </div>
      </Section>

      {/* ------------------------------------------------------------ features */}
      <Section id="features">
        <SectionHeading icon={Binary} eyebrow="3. Features" title={`${d.nFeaturesSource} inputs, encoded into ${d.nFeaturesEncoded} columns`}>
          Demographics, lifestyle, eight chronic-condition flags, coverage and income,
          plus five engineered features that a purely additive model could not
          otherwise represent.
        </SectionHeading>
        <div className="grid gap-4 sm:grid-cols-2">
          <div className="card p-4">
            <h4 className="text-[14px] font-semibold">Engineered features, and why each exists</h4>
            <ul className="mt-2 space-y-2 text-[13px] leading-relaxed text-[var(--color-ink-soft)]">
              <li><strong>Smoking × obesity</strong> — the interaction named in the brief. Two separate coefficients can never express “worse together than apart”.</li>
              <li><strong>Chronic condition count</strong> — managing four conditions at once is costlier than four people with one each.</li>
              <li><strong>Obesity flag</strong> — clinical risk turns at BMI 30 rather than rising smoothly.</li>
              <li><strong>Aged 65+</strong> — Medicare eligibility changes both spending and who records it.</li>
              <li><strong>Multimorbidity (3+)</strong> — a threshold widely used in health services research.</li>
            </ul>
          </div>
          <div className="card border-[var(--color-accent)]/30 bg-[var(--color-accent-soft)] p-4">
            <h4 className="flex items-center gap-2 text-[14px] font-semibold">
              <Gavel size={15} className="text-[var(--color-accent)]" /> Race is deliberately excluded
            </h4>
            <p className="mt-2 text-[13px] leading-relaxed text-[var(--color-ink-soft)]">
              Race and ethnicity are loaded from the survey but never given to any
              model. Pricing on race is unlawful in most jurisdictions and indefensible
              regardless. The variable is kept only so the finished model can be
              <em> audited</em> for unequal error rates across race groups — which is
              reported in section 8, because excluding a variable does not by itself
              guarantee an even-handed model.
            </p>
          </div>
        </div>
      </Section>

      {/* ---------------------------------------------------------------- leak */}
      <Section id="leakage">
        <SectionHeading icon={AlertTriangle} eyebrow="4. Target leakage" title="The mistake that would have faked the accuracy">
          MEPS has no risk-tier column, so one had to be created. Following Option A
          of the brief, tiers are the tertiles of total 2024 expenditure.
        </SectionHeading>
        <div className="card p-5">
          <div className="grid gap-4 sm:grid-cols-3">
            {tiers.map((t, i) => (
              <div key={t} className="rounded-xl p-3" style={{ background: `color-mix(in srgb, ${TIER_COLORS[i]} 10%, white)` }}>
                <div className="text-[13px] font-semibold" style={{ color: TIER_COLORS[i] }}>{t}</div>
                <div className="mt-1 text-[13px] tabular-nums text-[var(--color-ink-soft)]">
                  {i === 0 && `under ${money(cls.tierCuts[0])}`}
                  {i === 1 && `${money(cls.tierCuts[0])} – ${money(cls.tierCuts[1])}`}
                  {i === 2 && `over ${money(cls.tierCuts[1])}`}
                </div>
              </div>
            ))}
          </div>
          <Note>
            Because expenditure <em>defines</em> the label, feeding expenditure to the
            classifier would produce near-perfect accuracy that means nothing. Two
            safeguards are in the code: the feature list is built independently of the
            target, and an assertion fails the run outright if the target or the
            survey weight ever appears among the features. The cut points themselves
            are computed on the training split alone and then frozen, so the test set
            contributes nothing even to the definition of the labels.
          </Note>
        </div>
      </Section>

      {/* ------------------------------------------------------- task A models */}
      <Section id="regression">
        <SectionHeading icon={Sigma} eyebrow="5. Task A — cost prediction" title="Predicting the annual bill">
          Seven approaches were fitted and compared on the same held-out people.
          The interesting result is not which won, but which failed and why.
        </SectionHeading>

        <div className="card mb-5 p-5">
          <h4 className="mb-3 text-[14px] font-semibold">Every model, measured on the same {d.nTest.toLocaleString()} held-out people</h4>
          <Table
            head={["Model", "MAE", "RMSE", "R²", "Median error"]}
            highlight={0}
            rows={[
              ["Tweedie GLM · deployed", money(reg.tweedieGlm.mae), money(reg.tweedieGlm.rmse), n(reg.tweedieGlm.r2), money(reg.tweedieGlm.medae)],
              ["XGBoost, Tweedie objective", money(reg.xgboostTweedie.mae), money(reg.xgboostTweedie.rmse), n(reg.xgboostTweedie.r2), money(reg.xgboostTweedie.medae)],
              ["Two-part model, calibrated", money(reg.twoPartCalibrated.mae), money(reg.twoPartCalibrated.rmse), n(reg.twoPartCalibrated.r2), money(reg.twoPartCalibrated.medae)],
              ["OLS on raw dollars", money(reg.olsRawDollars.mae), money(reg.olsRawDollars.rmse), n(reg.olsRawDollars.r2), money(reg.olsRawDollars.medae)],
              ["Predict the training mean", money(reg.meanBaseline.mae), money(reg.meanBaseline.rmse), n(reg.meanBaseline.r2), money(reg.meanBaseline.medae)],
              ["Single-stage log + smearing", money(reg.singleStageLogSmearing.mae), money(reg.singleStageLogSmearing.rmse), n(reg.singleStageLogSmearing.r2), money(reg.singleStageLogSmearing.medae)],
            ]}
          />
          <Note>
            MAE is the average miss in dollars, and is the honest headline. R² is low
            for every model here, and that is not a bug: individual annual medical
            spending is close to unpredictable from demographics, because most of the
            variance comes from events — an accident, a new diagnosis — that no survey
            question can anticipate. This is a known ceiling in health economics, not
            a failure of tuning.
          </Note>
        </div>

        <div className="card mb-5 border-[var(--color-high)]/30 bg-[var(--color-high-soft)] p-5">
          <h4 className="flex items-center gap-2 text-[14px] font-semibold">
            <FlaskConical size={15} className="text-[var(--color-high)]" />
            The result that went wrong, and what it taught
          </h4>
          <p className="mt-2 text-[13.5px] leading-relaxed text-[var(--color-ink-soft)]">
            The brief prescribes training on log(charges) and transforming back with
            Duan's smearing estimator. That was implemented — and it failed badly. The
            last row of the table is a real run: MAE {money(reg.singleStageLogSmearing.mae)},
            R² {n(reg.singleStageLogSmearing.r2, 2)}, far <em>worse</em> than simply
            guessing the average for everybody.
          </p>
          <p className="mt-2 text-[13.5px] leading-relaxed text-[var(--color-ink-soft)]">
            The cause: smearing multiplies by the mean of exp(residual). With
            residuals this long-tailed, that mean is dominated by a handful of enormous
            ones, giving a correction factor of {m.part2.smearing.toFixed(2)} and
            systematic over-prediction of everybody. Two fixes were tried. A
            mean-preserving calibration factor ({reg.calibrationFactor.toFixed(2)},
            fitted out-of-fold so that total predicted spend matches total observed
            spend) rescues the two-part model. The better fix was to stop
            back-transforming at all.
          </p>
          <p className="mt-2 text-[13.5px] leading-relaxed text-[var(--color-ink-soft)]">
            A <strong>Tweedie distribution</strong> with power between 1 and 2 is a
            compound Poisson–Gamma: a spike of probability at exactly zero, plus a
            continuous right-skewed part. That is a literal description of annual
            medical spending, which is why general insurers price on it. With a log
            link it models expected dollars directly, so there is no back-transform
            and no smearing problem. The power was chosen by cross-validated MAE:
            {" "}{reg.tweediePower}.
          </p>
        </div>

        <Frame
          title="Does the ranking hold up? Decile lift"
          height={260}
          caption={
            <>Everyone in the test set, sorted by predicted cost and cut into ten equal
              groups. Teal is what the model predicted; dark is what those people
              actually spent. The costliest tenth really did spend{" "}
              <strong>{reg.topBottomDecileRatio.toFixed(1)}×</strong> what the cheapest
              tenth spent — which is the property that makes a pricing model useful,
              and it is invisible in R².</>
          }
        >
          <LiftChart data={reg.decileLift} />
        </Frame>
        <Legend items={[
          { name: "Predicted mean", color: "var(--color-accent)" },
          { name: "Actual mean", color: "var(--color-ink)" },
        ]} />
      </Section>

      {/* ------------------------------------------------- task A part 1 detail */}
      <Section id="anyspend">
        <SectionHeading icon={GitBranch} eyebrow="6. The two-part model" title="Part one: does this person spend anything at all?">
          {m.part1.description} {pct(m.part1.positiveRate, 1)} of held-out adults did.
        </SectionHeading>
        <div className="card mb-5 p-5">
          <Table
            head={["Model", "CV ROC-AUC", "Test ROC-AUC", "PR-AUC", "Brier score"]}
            highlight={m.part1.models.findIndex((x: any) => x.model === m.part1.deployed)}
            rows={m.part1.models.map((x: any) => [
              x.model + (x.model === m.part1.deployed ? " · deployed" : ""),
              `${n(x.cvRocAuc)} ± ${n(x.cvRocAucStd)}`, n(x.rocAuc), n(x.prAuc), n(x.brier),
            ])}
          />
          <Note>
            The Brier score measures whether the probabilities themselves are
            trustworthy, not merely whether the ranking is right — it matters here
            because the two-part model multiplies by this probability, so a
            badly-calibrated part one corrupts the dollar figure downstream.
          </Note>
        </div>
        <div className="grid gap-4 lg:grid-cols-2">
          <Frame title="ROC curve" caption="How well the classifier separates spenders from non-spenders at every threshold. The dashed line is chance.">
            <CurveChart diagonal series={[{ name: "ROC", color: "var(--color-accent)", x: m.part1.roc.fpr, y: m.part1.roc.tpr }]}
              xLabel="False positive rate" yLabel="True positive rate" />
          </Frame>
          <Frame title="Calibration" caption="Predicted probability against what actually happened. Points on the diagonal mean the stated probabilities can be taken at face value.">
            <CurveChart diagonal
              series={[{ name: "Observed", color: "var(--color-accent)",
                x: m.part1.calibration.map((c: any) => c.predicted),
                y: m.part1.calibration.map((c: any) => c.observed) }]}
              xLabel="Predicted probability" yLabel="Observed frequency" />
          </Frame>
        </div>
      </Section>

      {/* --------------------------------------------------- task B classification */}
      <Section id="classification">
        <SectionHeading icon={BarChart3} eyebrow="7. Task B — risk stratification" title="Sorting people into Low, Medium and High">
          Three tiers of equal size, so a random guesser scores about 0.33. Class
          weights are balanced, and macro-F1 is the selection metric because it
          weights all three tiers equally rather than letting the easy ones carry the
          score.
        </SectionHeading>

        <div className="card mb-5 p-5">
          <Table
            head={["Model", "CV macro-F1", "Test macro-F1", "Accuracy", "High-tier recall", "Macro ROC-AUC"]}
            highlight={cls.models.findIndex((x: any) => x.model === cls.deployed)}
            rows={cls.models.map((x: any) => [
              x.model + (x.model === cls.deployed ? " · deployed" : ""),
              `${n(x.cvMacroF1)} ± ${n(x.cvMacroF1Std)}`, n(x.macroF1), n(x.accuracy),
              n(x.highRecall), n(x.macroRocAuc),
            ])}
          />
          <Note>
            The three real models land within about 0.01 macro-F1 of one another —
            comfortably inside the fold-to-fold noise. When models tie, the tiebreak
            should be something other than the third decimal: the logistic regression
            is deployed because it serialises to 14 KB, runs in the browser, and gives
            <em> exact</em> per-person attributions rather than approximate ones. The
            95% bootstrap interval on its macro-F1 is [{n(cls.macroF1CI95[0])}, {n(cls.macroF1CI95[1])}].
          </Note>
        </div>

        <div className="grid gap-4 lg:grid-cols-2">
          <div className="card p-5">
            <h4 className="mb-1 text-[14px] font-semibold">Confusion matrix</h4>
            <p className="mb-4 text-[12.5px] leading-relaxed text-[var(--color-ink-soft)]">
              Teal on the diagonal is correct. Red off it is wrong, and how wrong
              matters: a Low person called High is a lost customer, a High person
              called Low is an unpriced loss.
            </p>
            <ConfusionMatrix matrix={cls.confusionMatrix} labels={tiers} />
          </div>

          <div className="card p-5">
            <h4 className="mb-1 text-[14px] font-semibold">Precision and recall per tier</h4>
            <p className="mb-4 text-[12.5px] leading-relaxed text-[var(--color-ink-soft)]">
              Precision: when it says this tier, how often is it right. Recall: of
              everyone truly in this tier, how many it found.
            </p>
            <Table
              head={["Tier", "Precision", "Recall", "F1", "People"]}
              rows={tiers.map((t) => [
                t, n(cls.perClass[t].precision), n(cls.perClass[t].recall),
                n(cls.perClass[t].f1), cls.perClass[t].support,
              ])}
            />
            <Note>
              The Medium tier is the hard one, and that is expected rather than
              disappointing: it is defined by two arbitrary cut points with genuinely
              similar people sitting on either side. Low and High are separated by real
              differences, so the model finds them.
            </Note>
          </div>
        </div>

        <div className="mt-4 grid gap-4 lg:grid-cols-2">
          <Frame title="Precision–recall curves, one per tier"
            caption="Drawn one-vs-rest. Each tier holds about a third of people, so a useless model would sit flat at 0.33.">
            <CurveChart
              series={tiers.map((t, i) => ({
                name: t, color: TIER_COLORS[i],
                x: cls.prCurves[t].recall, y: cls.prCurves[t].precision,
              }))}
              xLabel="Recall" yLabel="Precision" />
          </Frame>
          <div className="card p-5">
            <h4 className="mb-1 text-[14px] font-semibold">Average precision by tier</h4>
            <p className="mb-4 text-[12.5px] leading-relaxed text-[var(--color-ink-soft)]">
              Area under each curve above, against the 0.333 a random model would get.
            </p>
            <BarChart max={1}
              data={tiers.map((t) => ({ label: t, value: cls.prCurves[t].ap }))}
              format={(v) => n(v)} />
            <Note>
              Missing a High-risk person is the costliest error an insurer can make, so
              the operating threshold is a business decision rather than a default.
              Lowering the threshold on P(High) below 0.5 trades precision for recall:
              {" "}
              {cls.highTierThresholds.slice(0, 3).map((t: any) =>
                `at ${t.threshold}, recall ${pct(t.recall, 0)} / precision ${pct(t.precision, 0)}`
              ).join("; ")}.
            </Note>
          </div>
        </div>
      </Section>

      {/* ------------------------------------------------------ explainability */}
      <Section id="explainability">
        <SectionHeading icon={Microscope} eyebrow="8. Explainability" title="What drives the model, and how we know">
          {m.explainability.method}
        </SectionHeading>

        <div className="grid gap-4 lg:grid-cols-2">
          <Frame title="Importance by question asked" height={330}
            caption="One-hot columns and missingness indicators rolled back up to the question a person actually answers, so the chart names something real.">
            <div className="h-full overflow-y-auto pr-1">
              <BarChart
                data={m.explainability.groupedImportance.slice(0, 12).map((r: any) => ({
                  label: FEATURE_LABELS[r.feature] ?? r.feature,
                  value: r.meanAbsContribution,
                }))}
                format={(v) => v.toFixed(3)} />
            </div>
          </Frame>
          <Frame title="Cross-check against TreeSHAP" height={330}
            caption={`The same quantity computed by TreeSHAP on the XGBoost challenger. Spearman rank agreement between the two methods is ${n(m.explainability.rankAgreementWithTreeShap, 2)} — they broadly read the same signal, which is reassurance that the deployed model is not relying on an artefact.`}>
            <div className="h-full overflow-y-auto pr-1">
              <BarChart color="var(--color-ink)"
                data={m.explainability.groupedImportance.slice(0, 12).map((r: any) => ({
                  label: FEATURE_LABELS[r.feature] ?? r.feature,
                  value: r.treeShap,
                }))}
                format={(v) => v.toFixed(3)} />
            </div>
          </Frame>
        </div>

        <div className="card mt-4 p-5">
          <h4 className="text-[14px] font-semibold">Why the attributions here are exact rather than approximate</h4>
          <p className="mt-2 text-[13.5px] leading-relaxed text-[var(--color-ink-soft)]">
            SHAP for a tree ensemble is an estimate. For a linear model it is a closed
            form: the contribution of feature <em>j</em> is its coefficient times how
            far that person's standardised answer sits from a fixed reference person.
            The contributions then sum to the person's score minus the reference
            score, with nothing left over. The training run verifies that identity
            numerically every time: the largest discrepancy across the whole test set
            is {m.explainability.additivityMaxError.toExponential(1)}, which is
            floating-point rounding.
          </p>
          <p className="mt-2 text-[13.5px] leading-relaxed text-[var(--color-ink-soft)]">
            Attributions are measured against a reference person rather than against
            zero for a specific reason. The one-hot dummies for region and the other
            categorical answers are collinear, so their raw coefficients are only
            identified up to a shared constant, and regularisation splits that constant
            arbitrarily. Differencing against a fixed reference cancels it exactly, and
            makes the explanation legible: “compared with a typical adult, here is what
            your answers did”.
          </p>
        </div>
      </Section>

      {/* ------------------------------------------------------------ fairness */}
      <Section id="fairness">
        <SectionHeading icon={Scale} eyebrow="9. Fairness audit" title="Does the model work equally well for everyone?">
          Race is not an input to any model here. That is necessary but not
          sufficient: a model can still perform unevenly across groups by leaning on
          correlated features. So the finished model is measured separately within
          each group.
        </SectionHeading>

        {([["race", "Race and ethnicity"], ["sex", "Sex"], ["povertyCategory", "Income band"]] as const).map(
          ([key, title]) => (
            <div key={key} className="card mb-4 p-5">
              <h4 className="mb-3 text-[14px] font-semibold">{title}</h4>
              <Table
                head={["Group", "People", "High-tier recall", "Macro-F1", "Mean cost error", "Actual mean cost"]}
                rows={m.fairness[key].map((g: any) => [
                  g.group, g.n, n(g.highRecall), n(g.macroF1), money(g.mae), money(g.meanActual),
                ])}
              />
            </div>
          ),
        )}

        <div className="card border-[var(--color-medium)]/30 bg-[var(--color-medium-soft)] p-5">
          <h4 className="flex items-center gap-2 text-[14px] font-semibold">
            <AlertTriangle size={15} className="text-[var(--color-medium)]" /> What the audit actually found
          </h4>
          <p className="mt-2 text-[13.5px] leading-relaxed text-[var(--color-ink-soft)]">
            The gaps are real and worth stating plainly. High-tier recall ranges from
            about {n(Math.min(...m.fairness.race.map((g: any) => g.highRecall)), 2)} to
            about {n(Math.max(...m.fairness.race.map((g: any) => g.highRecall)), 2)}
            {" "}across race groups — meaning the model finds high-cost people in some
            groups noticeably more reliably than in others. Some of the smaller groups
            have only a couple of hundred people in the test set, so their figures are
            unstable, but the direction is consistent enough not to dismiss.
          </p>
          <p className="mt-2 text-[13.5px] leading-relaxed text-[var(--color-ink-soft)]">
            Dollar errors also differ by group, largely because mean spending itself
            differs: a group that spends more has more room to be wrong about. Before
            anything like this went near a real pricing decision, these gaps would
            need to be the subject of the conversation, not a footnote to it.
          </p>
        </div>
      </Section>

      {/* -------------------------------------------------------------- limits */}
      <Section id="limits">
        <SectionHeading icon={BookOpen} eyebrow="10. Limitations" title="What this model cannot do">
          Stated in full, because a model's limits are part of its specification.
        </SectionHeading>
        <div className="grid gap-3 sm:grid-cols-2">
          {[
            ["Individual spending is close to unpredictable", `R² of about ${n(reg.tweedieGlm.r2, 2)} means most variation between people is not explained. This is the known ceiling for demographic-based cost models, because the biggest driver is unforeseeable events.`],
            ["Trained unweighted", "MEPS uses a complex survey design with person-level weights. Those weights are correct for population totals; they were not used for fitting, so these models describe the sample rather than the US population."],
            ["US prices, one year", "Costs reflect US healthcare in 2024. They do not transfer to other countries or, without inflation adjustment, to other years."],
            ["Adults only", "Age 18 and over, because BMI and smoking are adult-only survey items. Nothing here applies to children."],
            ["Self-reported", "Conditions, smoking and BMI are what respondents said, not what was measured. Self-report is known to under-state smoking and weight."],
            ["Association, not causation", "Every relationship here is correlational. Nothing in this model says that changing a feature would change a person's costs."],
          ].map(([t, b]) => (
            <div key={t} className="card p-4">
              <h4 className="text-[13.5px] font-semibold">{t}</h4>
              <p className="mt-1.5 text-[12.5px] leading-relaxed text-[var(--color-ink-soft)]">{b}</p>
            </div>
          ))}
        </div>
      </Section>

      {/* --------------------------------------------------------------- cite */}
      <Section id="citation">
        <SectionHeading icon={ScrollText} eyebrow="11. Data source" title="Citation and terms of use" />
        <div className="card p-5">
          <p className="text-[13.5px] leading-relaxed text-[var(--color-ink-soft)]">
            Agency for Healthcare Research and Quality. <em>Medical Expenditure Panel
            Survey, HC-256: 2024 Full Year Consolidated Data File.</em> Rockville, MD:
            AHRQ, August 2026.
          </p>
          <p className="mt-3 text-[13px] leading-relaxed text-[var(--color-ink-soft)]">
            MEPS data are free and public. Use is limited to statistical reporting and
            analysis, and AHRQ asks to be cited as the source. No attempt is made
            anywhere in this project to identify any individual respondent.
          </p>
        </div>
      </Section>
    </article>
  );
}

function bestF1(cls: any) {
  return cls.models.find((m: any) => m.model === cls.deployed)?.macroF1 ?? 0;
}
function baselineF1(cls: any) {
  return cls.models.find((m: any) => m.model.includes("baseline"))?.macroF1 ?? 0.333;
}
